### ISSUE TITLE
Scroll is not working after css update 

### ISSUE THREAD

**Issue by Anandkarn** [ashwinkshenoy/chatbot#2]

**Comment by ashwinkshenoy** [comment]
Thanks. Fixed the issue!

**Comment by Anandkarn** [comment]
I want to change the position of the chat bot widget(in the middle of the screen or on the left side). I have applied transform: translateX(*%) but it is not working, i mean it is not fixed. It overrides the fixed property. How to solve this issue?

**Comment by ashwinkshenoy** [comment]
Try adding class "center" to mybot tag Like this
`<mybot class="center"></mybot>`
or 'left' class
Hope this helps!
