### ISSUE TITLE
Does this automatically popup in a webpage?

### ISSUE THREAD

**Issue by leslyarun** [ashwinkshenoy/chatbot#5]
Hi, Is the chat widget can be made to automatically pop up in a web page?
Can it be made to show the notifications for incoming messages from dialogflow?
For example, if the chatbot is minimized and the chatbot receives a message, it should show to the user that it has received a message.

**Comment by ashwinkshenoy** [comment]
For dialog flow to work trigger message is important, if its minimised and trigger message is sent , once you receive a message from DF you can trigger open it!

**Comment by leslyarun** [comment]
@ashwinkshenoy I didn't get u. Can u please elaborate a bit more, please

**Comment by ashwinkshenoy** [comment]
Have a look @ [https://dialogflow.com/docs/getting-started/basics](https://dialogflow.com/docs/getting-started/basics)
