### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by VikramChathilla** [ashwinkshenoy/chatbot#8]
Hi Ashwin,
I have tried your code and changes are done as you mentioned in the file. But I'm not able to get result. And I have tried with your code without changing anything,still I'm facing the same Issue.
-> Do I need to do something in Google Dialogflow while taking the client Key?
 Can you help me in this.
![gittemp](https://user-images.githubusercontent.com/50819415/85145418-29748100-b26a-11ea-91bb-958ab5b81598.JPG)

**Comment by ashwinkshenoy** [comment]
Hi Vikram,
Sorry for the delay.
Not sure what the issue is here. Have you changed the `baseUrl ` & `accessToken` in `script.js` file to your credentials?
